CREATE DATABASE IF NOT EXISTS kotlindatabase;
USE kotlindatabase;

CREATE TABLE IF NOT EXISTS POSTS (
    POST_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '投稿ID',
    TITLE VARCHAR(2000) COMMENT 'タイトル',
    DELETE_FLG boolean default false COMMENT '削除フラグ',
    CREATE_DATE DATETIME default CURRENT_TIMESTAMP COMMENT '投稿日',
    PRIMARY KEY(POST_ID)
) COMMENT="TODO管理テーブル";