CREATE DATABASE IF NOT EXISTS kotlindatabase;
USE kotlindatabase;

CREATE TABLE IF NOT EXISTS POSTS (
    POST_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '投稿ID',
    TITLE VARCHAR(2000) COMMENT 'タイトル',
    TARGET_COMPLETE_DATE DATE COMMENT '完了日時',
    DELETE_FLG boolean default false COMMENT '削除フラグ',
    CREATE_DATE DATETIME default CURRENT_TIMESTAMP COMMENT '投稿日',
    UPDATE_DATE DATETIME default CURRENT_TIMESTAMP COMMENT '更新日',
    PRIMARY KEY(POST_ID)
) COMMENT="TODO管理テーブル";

CREATE TABLE IF NOT EXISTS USERS(
	USER_ID BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'ユーザーID',
	EMAIL VARCHAR(128) COMMENT 'メールアドレス',
	PASSWORD VARCHAR(256) COMMENT 'パスワード',
	PRIMARY KEY(USER_ID)
) COMMENT="ユーザーテーブル";